blank_issues_enabled: true
contact_links:
  - name: 💬 Forum
    url: https://community.ultralytics.com/
    about: Ask on Ultralytics Community Forum
  - name: Stack Overflow
    url: https://stackoverflow.com/search?q=YOLOv3
    about: Ask on Stack Overflow with 'YOLOv3' tag
